FROM nginx:alpine
ARG WORKING_DIR=/var/www/html/

COPY . ${WORKING_DIR}

# ARG WORKING_DIR=/var/www/html/

# COPY ${GITHUB_WORKSPACE} ${WORKING_DIR}

# RUN apt-get update \
#  && apt-get install -y software-properties-common python-pip curl nodejs

# WORKDIR ${WORKING_DIR}

# CMD [ "/bin/bash" ]