name: Build Fantasy Football Site Container

on:
  push:
    paths:
    - '.github/**'
    - 'nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Git checkout
    - uses: actions/checkout@v2

    # Login to Docker Hub
    - name: Docker login
      run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    # Build and publish Docker image
    - name: Docker build and push
      run: docker build -f ${GITHUB_WORKSPACE}/nginx/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: nginx
